In [1]:
from monstry.Builder import Builder
from monstry.DataCleaner import DataCleaner

In [2]:
json_file = './analisis_calidad_adultos_mayores/config/config.json'
builder = Builder( config_path = json_file)

Se ha creado usando un archivo de configuracion

In [3]:
adultos_mayores = DataCleaner(builder, 'adultos_mayores' )

Se ha cargado efectivamente el dataframe

        Informacion:
            _ get_completitud():
                Se obtienen la completutid de la tabla
            - get_exactitud():
                Se obtiene la exactitud de la tabla siempre y cuando los valores por default sean completados
                en el archivo de configuraciones o tengan un valor por defecto
            ----------------------------------------------------------------------------------------------------
            - get_resumen():
                Se obtiene un dataframe con el análisis de completitud y exactitud del dataset seleccionado

/home/anderson/Documents/analisis/monstry_goayvd/monstry/modules/dataframes_uri_def.py:26: DtypeWarning: Columns (14,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path)

In [4]:
adultos_mayores.get_completitud()
adultos_mayores.completitud

Analisis de completitud sin tener en cuenta ningún tipo de caracter especial, simplemente por valores nulos
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud

,COLUMNA,NOMBRE TABLA,REGISTROS TOTALES,CANTIDAD DE INCOMPLETOS,CANTIDAD DE COMPLETOS,PORCENTAJE COMPLETITUD
0,insertion_date,adultos_mayores,51523,0,51523,100.00
1,ultimo_examen,adultos_mayores,51523,17,51506,99.97
2,nrodocumento,adultos_mayores,51523,1,51522,100.00
3,fecha_formulario,adultos_mayores,51523,44009,7514,14.58
4,cuil,adultos_mayores,51523,44140,7383,14.33
5,localidad,adultos_mayores,51523,2657,48866,94.84
6,genero,adultos_mayores,51523,0,51523,100.00
7,apellido,adultos_mayores,51523,0,51523,100.00
8,altura,adultos_mayores,51523,1309,50214,97.46
9,fecha_alta_usuario,adultos_mayores,51523,18455,33068,64.18
10,tipo_documento,adultos_mayores,51523,0,51523,100.00
11,plan_estudio,adultos_mayores,51523,0,51523,100.00
12,cp,adultos_mayores,51523,6287,45236,87.80
13,nombre,adultos_mayores,51523,0,51523,100.00
14,provincia,adultos_mayores,51523,0,51523,100.00
15,calle,adultos_mayores,51523,45,51478,99.91
16,municipio,adultos_mayores,51523,51502,21,0.04
17,fecha_nacimiento,adultos_mayores,51523,0,51523,100.00
18,estado,adultos_mayores,51523,0,51523,100.00

In [5]:
adultos_mayores.get_exactitud()
adultos_mayores.exactitud

Analisis de completitud sin tener en cuenta ningún tipo de caracter especial, simplemente por valores nulos
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud
Analisis de exactitud finalizado
* Para observar los resultados solo de "Exactitud" visualizar con .exactitud

               COLUMNA  EXACTO  INEXACTO  PORCENTAJE DE EXACTITUD
0               altura   48924      1278                    97.45
1               genero   51523         0                   100.00
2         nrodocumento   51483        38                    99.93
3               estado   51523         0                   100.00
4            municipio      21         0                   100.00
5            provincia   51523         0                   100.00
6               nombre   51504        18                    99.97
7         plan_estudio   51523         0                   100.00
8       tipo_documento   51523         0                   100.00
9             apellido   51520         2                   100.00
10           localidad   48374       491                    99.00
11               calle   51462         0                   100.00
12                  cp   44735       488                    98.92
13                cuil    7321        61                    99.17
14    fecha_nacimiento   51362         0                   100.00
15  fecha_alta_usuario   33068         0                   100.00
16    fecha_formulario    7514         0                   100.00
17       ultimo_examen   51506         0                   100.00
18      insertion_date   51523         0                   100.00

In [6]:
adultos_mayores.estado_columna()

        Conteo de cantidad de registros por caracteres determinados como nulls por el usuario
        como valores de default.

,CANTIDAD VALORES UNICOS,CANTIDAD VALORES DUPLICADOS,TOTAL DE NULOS,PORCENTAJE DE NULOS,",",.,',-,_,,VACIO,prueba,dsvf,38.625.873,O2744285006,0000-00-00,1900-01-00
estado,8,51515,0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0
fecha_nacimiento,16738,34785,0,0.00,0,0,0,0,0,0,0,0,0,0,0,159,2
municipio,21,0,51502,99.96,0,0,0,0,0,0,0,0,0,0,0,0,0
calle,20490,30988,45,0.09,1,11,0,4,0,0,0,0,0,0,0,0,0
provincia,25,51498,0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0
nombre,29548,21975,0,0.00,0,0,0,0,0,0,0,1,0,0,0,0,0
cp,2026,43210,6287,12.20,0,7,0,6,0,0,0,0,0,0,0,0,0
plan_estudio,2,51521,0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0
tipo_documento,8,51515,0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0
fecha_alta_usuario,992,32076,18455,35.82,0,0,0,0,0,0,0,0,0,0,0,0,0
altura,7867,42347,1309,2.54,0,7,0,5,0,0,0,0,0,0,0,0,0
apellido,24905,26618,0,0.00,0,0,0,0,0,0,0,1,0,0,0,0,0
genero,3,51520,0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0
localidad,3092,45774,2657,5.16,0,0,0,0,0,0,0,0,1,0,0,0,0
cuil,7380,3,44140,85.67,0,0,0,0,0,0,0,0,0,0,1,0,0
fecha_formulario,988,6526,44009,85.42,0,0,0,0,0,0,0,0,0,0,0,0,0
nrodocumento,51510,12,1,0.00,0,0,0,0,0,0,0,0,0,1,0,0,0
ultimo_examen,1609,49897,17,0.03,0,0,0,0,0,0,0,0,0,0,0,0,0
insertion_date,1,51522,0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
adultos_mayores.get_resumen()

Analisis de completitud sin tener en cuenta ningún tipo de caracter especial, simplemente por valores nulos
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud
Analisis de exactitud finalizado
* Para observar los resultados solo de "Exactitud" visualizar con .exactitud

,COLUMNA,NOMBRE TABLA,REGISTROS TOTALES,CANTIDAD DE INCOMPLETOS,CANTIDAD DE COMPLETOS,PORCENTAJE COMPLETITUD,EXACTO,INEXACTO,PORCENTAJE DE EXACTITUD
0,insertion_date,adultos_mayores,51523,0,51523,100.00,51523,0,100.00
1,ultimo_examen,adultos_mayores,51523,17,51506,99.97,51506,0,100.00
2,nrodocumento,adultos_mayores,51523,1,51522,100.00,51483,38,99.93
3,fecha_formulario,adultos_mayores,51523,44009,7514,14.58,7514,0,100.00
4,cuil,adultos_mayores,51523,44140,7383,14.33,7321,61,99.17
5,localidad,adultos_mayores,51523,2657,48866,94.84,48374,491,99.00
6,genero,adultos_mayores,51523,0,51523,100.00,51523,0,100.00
7,apellido,adultos_mayores,51523,0,51523,100.00,51520,2,100.00
8,altura,adultos_mayores,51523,1309,50214,97.46,48924,1278,97.45
9,fecha_alta_usuario,adultos_mayores,51523,18455,33068,64.18,33068,0,100.00
10,tipo_documento,adultos_mayores,51523,0,51523,100.00,51523,0,100.00
11,plan_estudio,adultos_mayores,51523,0,51523,100.00,51523,0,100.00
12,cp,adultos_mayores,51523,6287,45236,87.80,44735,488,98.92
13,nombre,adultos_mayores,51523,0,51523,100.00,51504,18,99.97
14,provincia,adultos_mayores,51523,0,51523,100.00,51523,0,100.00
15,calle,adultos_mayores,51523,45,51478,99.91,51462,0,100.00
16,municipio,adultos_mayores,51523,51502,21,0.04,21,0,100.00
17,fecha_nacimiento,adultos_mayores,51523,0,51523,100.00,51362,0,100.00
18,estado,adultos_mayores,51523,0,51523,100.00,51523,0,100.00

In [8]:

adultos_mayores.to_csv(file_name = "adultos_mayores")

/home/anderson/Documents/analisis/monstry_goayvd/monstry

In [9]:
adultos_mayores.__inexactos__()

-----------------------------------------------altura-----------------------------------------------
14               lote 134
32             51 TORRE 2
67     Manzana 12 Lote 30
135           Av escalada
144            Av caseros
Name: altura, dtype: object
--------------------------------------------nrodocumento--------------------------------------------
190       117385
195       136832
199       178312
202    192622777
215       308222
Name: nrodocumento, dtype: object
-----------------------------------------------nombre-----------------------------------------------
1458       Esther R.
3424    FLORENCIA M.
3565    GRISELDA .E.
6551       BENEDA B.
7517      JOSE LUIS|
Name: nombre, dtype: object
----------------------------------------------apellido----------------------------------------------
21492               Marcial.
26552    ROTONDO DELLEPIANIº
Name: apellido, dtype: object
---------------------------------------------localidad----------------------------------------------
61                               743
152    Buenase esperanza  (San luis)
168                     23 DE AGOSTO
178                      16 DE JULIO
652       villa luzuriaga(San Justo)
Name: localidad, dtype: object
-------------------------------------------------cp-------------------------------------------------
177    B1752
282      224
284    B7600
293    B1657
294    B1827
Name: cp, dtype: object
------------------------------------------------cuil------------------------------------------------
65        329774740
10872    2723384890
11195    2723580181
11636    2723856862
12062    2724178991
Name: cuil, dtype: object

In [10]:
adultos_mayores.__exactos__()

-----------------------------------------------altura-----------------------------------------------
0    1232
1    5382
2     658
3    1744
4    5658
Name: altura, dtype: object
--------------------------------------------nrodocumento--------------------------------------------
0    11111120
1    11805551
2    14059444
3    14128759
4    16252608
Name: nrodocumento, dtype: object
-----------------------------------------------nombre-----------------------------------------------
1        Liliana Alicia
2       Griselda Susana
3             Ana Maria
4      Graciela Beatriz
5    MARISA EDIT ISABEL
Name: nombre, dtype: object
----------------------------------------------apellido----------------------------------------------
1             MARTINEZ
2    Benítez DE Ninnis
3               Fulini
4               Alanis
5             BERTUZZI
Name: apellido, dtype: object
---------------------------------------------localidad----------------------------------------------
1                     CAPITAL FEDERAL
2                          Hurlingham
3                           ituzaingo
4                        BILLINGHURST
5    RESTO DE LA PCIA DE BUENOS AIRES
Name: localidad, dtype: object
-------------------------------------------------cp-------------------------------------------------
0    1234
1    1419
2    1686
3    3302
4    1650
Name: cp, dtype: object
------------------------------------------------cuil------------------------------------------------
4     27162526087
7     27182739222
10    20628530042
14    27229447128
15    20230503827
Name: cuil, dtype: object