In [1]:
from monstry.Builder import Builder
from monstry.DataCleaner import DataCleaner

In [2]:

json_file = './analisis_calidad_iel_cfp/config/config.json'
builder = Builder( config_path = json_file)

Se ha creado usando un archivo de configuracion

In [3]:
iel_cfp = DataCleaner(builder, 'iel_cfp' )

Se ha cargado efectivamente el dataframe

        Informacion:
            _ get_completitud():
                Se obtienen la completutid de la tabla
            - get_exactitud():
                Se obtiene la exactitud de la tabla siempre y cuando los valores por default sean completados
                en el archivo de configuraciones o tengan un valor por defecto
            ----------------------------------------------------------------------------------------------------
            - get_resumen():
                Se obtiene un dataframe con el análisis de completitud y exactitud del dataset seleccionado

In [4]:
iel_cfp.get_completitud()
iel_cfp.completitud

Analisis de completitud sin tener en cuenta ningún tipo de caracter especial, simplemente por valores nulos
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud

,COLUMNA,NOMBRE TABLA,REGISTROS TOTALES,CANTIDAD DE INCOMPLETOS,CANTIDAD DE COMPLETOS,PORCENTAJE COMPLETITUD
0,insert_into_dl_timestamp,iel_cfp,24245,0,24245,100.00
1,nivel_estudios,iel_cfp,24245,0,24245,100.00
2,profesion,iel_cfp,24245,0,24245,100.00
3,localidadprovincia,iel_cfp,24245,18330,5915,24.40
4,provincia,iel_cfp,24245,0,24245,100.00
5,direccion_estudiante,iel_cfp,24245,207,24038,99.15
6,fecha_nacimiento,iel_cfp,24245,0,24245,100.00
7,sexo,iel_cfp,24245,0,24245,100.00
8,nacionalidad,iel_cfp,24245,0,24245,100.00
9,telefono,iel_cfp,24245,3410,20835,85.94
10,email,iel_cfp,24245,0,24245,100.00
11,nrodocumento,iel_cfp,24245,5,24240,99.98
12,tipo_documento,iel_cfp,24245,0,24245,100.00
13,nombre,iel_cfp,24245,0,24245,100.00
14,apellido,iel_cfp,24245,0,24245,100.00
15,fechacreacion,iel_cfp,24245,0,24245,100.00
16,estado,iel_cfp,24245,0,24245,100.00
17,sorteo,iel_cfp,24245,24245,0,0.00
18,motivo,iel_cfp,24245,13209,11036,45.52
19,trabajo_relacionado,iel_cfp,24245,12974,11271,46.49
20,inscripcion,iel_cfp,24245,0,24245,100.00
21,comision,iel_cfp,24245,0,24245,100.00
22,curso,iel_cfp,24245,0,24245,100.00
23,direccion_escuela,iel_cfp,24245,0,24245,100.00
24,sede,iel_cfp,24245,0,24245,100.00
25,nivel,iel_cfp,24245,0,24245,100.00

In [5]:
iel_cfp.get_exactitud()
iel_cfp.exactitud

Analisis de completitud sin tener en cuenta ningún tipo de caracter especial, simplemente por valores nulos
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud

/home/anderson/Documents/analisis/monstry_goayvd/venv/lib/python3.10/site-packages/pandas/core/dtypes/astype.py:189: RuntimeWarning: invalid value encountered in cast
  return values.astype(dtype, copy=copy)

⚠️WARNING:
	LA COLUMNA "sorteo" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
Analisis de exactitud finalizado
* Para observar los resultados solo de "Exactitud" visualizar con .exactitud

                     COLUMNA  EXACTO  INEXACTO  PORCENTAJE DE EXACTITUD
0               nrodocumento   24134       106                    99.56
1                       sexo   24245         0                   100.00
2                   telefono   20776        59                    99.72
3                      email   24239         6                    99.98
4                inscripcion   24245         0                   100.00
5              fechacreacion   24245         0                   100.00
6           fecha_nacimiento   24245         0                   100.00
7   insert_into_dl_timestamp   24245         0                   100.00
8          direccion_escuela   24245         0                   100.00
9       direccion_estudiante   24038         0                   100.00
10       trabajo_relacionado   11271         0                   100.00
11                    estado   24245         0                   100.00
12                      sede   24245         0                   100.00
13                     curso   23519       726                    97.01
14                  comision   24245         0                   100.00
15                     nivel   24245         0                   100.00
16                    motivo   11036         0                   100.00
17                    sorteo       0         0                     0.00
18                  apellido   24245         0                   100.00
19                    nombre   24244         1                   100.00
20            tipo_documento   24245         0                   100.00
21              nacionalidad   24244         1                   100.00
22                 provincia   24245         0                   100.00
23        localidadprovincia    5859        56                    99.05
24                 profesion    8787     15458                    36.24
25            nivel_estudios   24245         0                   100.00

In [6]:
iel_cfp.analisis_por_categoria(*iel_cfp.columnas)

----------------------------------------------------------------------------------------------------
Filas totales:
 24245

Registros con variable "nivel":
 24245

Cantidad de nulos:
 0

Valores distintos:
 ['Formación Profesional']

Cantidad de filas por valor:
 nivel
Formación Profesional    24245
Name: nivel, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 24245

Registros con variable "sede":
 24245

Cantidad de nulos:
 0

Valores distintos:
 ['C.F.P. Nº 10 Monserrat' 'C.F.P. Nº 18' 'C.F.P. Nº 34' 'C.F.P. Nº 24'
 'C.F.P. Nº 15 - Villa 21-24' 'C.F.P. Nº 25'
 'C.F.P. Nº 12 San Nicolas, Tucuman 615' 'C.F.P. Nº 10 Flores'
 'C.F.P. Nº 13' 'C.F.P. Nº 07' 'C.F.P. Nº 20'
 'C.F.P. Nº 12 Balvanera, Tucuman 2214' 'C.F.P. Nº 33' 'C.F.P. Nº 31'
 'C.F.P. Nº 19 - Parroquia Santa Elisa' 'C.F.P. Nº 06' 'C.F.P. Nº 30'
 'C.F.P. Nº 32' 'C.F.P. Nº 02 - Brandsen' 'C.F.P. Nº 10 - Urquiza'
 'C.F.P. Nº 10 San Nicolas, Mitre' 'C.F.P. Nº 39' 'C.F.P. Nº 08'
 'C.F.P. Nº 28 - Monserrat' 'C.F.P. N° 38' 'C.F.P. Nº 21'
 'C.F.P. Nº 10 Chacarita' 'C.F.P. Nº 29' 'C.F.P. Nº 11 Chacarita'
 'C.F.P. Nº 04 - Soldado de la Frontera'
 'C.F.P. Nº 23 - Combate de los Pozos' 'C.F.P. Nº 28 - Balvanera'
 'C.F.P. Nº 01' 'C.F.P. Nº 28 - Colegiales' 'C.F.P. Nº 17'
 'C.F.P. Nº 04 - Carhue' 'C.F.P. Nº 37' 'C.F.P. Nº 11 Almagro'
 'C.F.P. Nº 11 Mataderos' 'C.F.P. Nº 03' 'C.F.P. Nº 08 - SMATA'
 'C.F.P. Nº 19' 'Escuela Municipal de la Joya'
 'C.F.P. Nº 34 - Casa Pío IX' 'C.F.P. Nº 05' 'C.F.P. Nº 02 - Carrillo'
 'C.F.P. Nº 14' 'C.F.P. Nº 26 - San Cristobal'
 'C.F.P. Nº 27 - San Telmo, Azopardo' 'C.F.P. Nº 34 - Casa León XIII'
 'C.F.P. Nº 27 - San Telmo, Peru' 'C.F.P. Nº 09 Barracas, Río Cuarto'
 'C.F.P. Nº 40' 'C.F.P. Nº 19 - Parroquia Santa Rosa de Lima'
 'C.F.P. Nº 22' 'C.F.P. Nº 16 - Castañares'
 'C.F.P. Nº 28 - Parque Patricios' 'C.F.P. Nº 36 - Mataderos'
 'C.F.P. Nº 36' 'C.F.P. Nº 16 - Bogotá' 'C.F.P. Nº 17 - Chutro'
 'C.F.P. Nº 26 - Belgrano' 'C.F.P. Nº 26 - Liniers'
 'C.F.P. Nº 04 - Segurola' 'C.F.P. Nº 19 - Vicaría Devoto'
 'C.F.P. Nº 12 Balvanera, Lavalle' 'C.F.P. Nº 10 San Nicolas, Rivadavia'
 'C.F.P. Nº 26 - Villa Devoto' 'C.F.P. Nº 16 CIFA']

Cantidad de filas por valor:
 sede
C.F.P. Nº 16 CIFA                                1
C.F.P. Nº 26 - Villa Devoto                      1
C.F.P. Nº 10 San Nicolas, Rivadavia              2
C.F.P. Nº 16 - Bogotá                            8
C.F.P. Nº 26 - Belgrano                         13
C.F.P. Nº 27 - San Telmo, Azopardo              14
C.F.P. Nº 12 Balvanera, Lavalle                 14
C.F.P. Nº 17 - Chutro                           15
C.F.P. Nº 04 - Segurola                         17
C.F.P. Nº 19 - Vicaría Devoto                   22
C.F.P. Nº 10 Monserrat                          28
C.F.P. Nº 26 - Liniers                          48
C.F.P. Nº 19 - Parroquia Santa Elisa            55
C.F.P. Nº 14                                    63
C.F.P. Nº 36 - Mataderos                        91
C.F.P. Nº 19 - Parroquia Santa Rosa de Lima     93
C.F.P. Nº 39                                   105
C.F.P. Nº 36                                   121
C.F.P. Nº 34 - Casa León XIII                  134
C.F.P. Nº 19                                   144
Name: sede, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 24245

Registros con variable "direccion_escuela":
 24245

Cantidad de nulos:
 0

Valores distintos:
 ['CHACABUCO 170' 'PUEYRREDON AV. 860' 'QUINQUELA MARTIN, BENITO 1171'
 'MORON 2538' 'PEPIRI 1462' 'PASEO COLON AV. 1318' 'TUCUMAN 651'
 'LA PORTEÑA 14' 'TUCUMAN 1647' 'RAMSAY 2250' 'DELGADO 769' 'TUCUMAN 2214'
 'PASEO COLON AV. 731' 'PICHINCHA 467' 'SALTA 2290' 'ASAMBLEA AV. 153'
 'MARMOL, JOSE 1350' 'SOLIS 773' 'BRANDSEN 2570' 'MONROE 5354'
 'MITRE, BARTOLOME 970' 'MATANZA 2781' 'MEDRANO AV. 162'
 'REPUBLICA BOLIVARIANA DE VENEZUELA 340'
 'PERETTE, CARLOS H. y CALLE 10 (NO OFICIAL)' 'RIVADAVIA AV. 413'
 'FRAGA 638' 'DIAZ VELEZ AV. 4093' 'DORREGO AV. 690'
 'SOLDADO DE LA FRONTERA AV. 5140' 'COMBATE DE LOS POZOS 1103'
 'PERON, JUAN DOMINGO, TTE. GENERAL 2085' 'RIO CUARTO 1993'
 'FREIRE, RAMON, CAP. GRAL. 929' 'RAWSON 42' 'CARHUE 2970'
 'CHUTRO, PEDRO, PROF., DR. 3003' 'SPEGAZZINI CARLOS 450'
 'CASTRO, EMILIO AV. 7680' 'HUMBERTO 1° 2260' 'MAZA 851' 'GUARANI 272'
 'LEZICA 3955' 'YAPEYU 197' 'SENILLOSA 206' 'CARRILLO, RAMON, DR. 375'
 'MITRE, BARTOLOME 3540' 'RINCON 1044' 'AZOPARDO 1181' 'DORREGO 2124'
 'PERU 823' 'RIO CUARTO y MONTESQUIEU' 'ESCALADA AV. 2350' 'PASCO 434'
 '24 DE NOVIEMBRE 40' 'CASTAÑARES AV. 2650' 'JUJUY AV. 1738'
 'MURGUIONDO 2105' 'LOS PATOS 3080' 'BOGOTA 115' 'CIUDAD DE LA PAZ 2749'
 'MONTIEL 153' 'SEGUROLA AV. 1949' 'ARGERICH 3718' 'LAVALLE 1994'
 'RIVADAVIA AV. 1445' 'VARELA, JOSE PEDRO 5287'
 'CASTAÑARES AV. y ESCALADA AV.']

Cantidad de filas por valor:
 direccion_escuela
VARELA, JOSE PEDRO 5287            1
CASTAÑARES AV. y ESCALADA AV.      1
RIVADAVIA AV. 1445                 2
BOGOTA 115                         8
CIUDAD DE LA PAZ 2749             13
LAVALLE 1994                      14
AZOPARDO 1181                     14
SEGUROLA AV. 1949                 17
ARGERICH 3718                     22
CHACABUCO 170                     28
MONTIEL 153                       48
SALTA 2290                        55
MITRE, BARTOLOME 3540             63
MURGUIONDO 2105                   91
PASCO 434                         93
MATANZA 2781                     105
LOS PATOS 3080                   121
DORREGO 2124                     134
GUARANI 272                      144
PASEO COLON AV. 1318             153
Name: direccion_escuela, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 24245

Registros con variable "curso":
 24245

Cantidad de nulos:
 0

Valores distintos:
 ['Portugués  I' 'Técnicas de liquidación de sueldos y jornales'
 'PASTELERO' 'Operador de informática para administración y gestión'
 'Auxiliar en cerámica i' 'ARTESANIAS Y MANUALIDADES' 'COCINERO'
 'Gestión total de calidad ii' 'Inglés básico II'
 'MASAJES CORPORALES ARMONIZADORES Y ESTETICOS  I'
 'Diseño gráfico asistido por computadoras  iii'
 'OPERADOR DE INFORMÁTICA PARA ADMINISTRACIÓN Y GESTIÓN '
 'DECORADOR ARTESANAL DE TORTAS (MODULO I)'
 'MONTADOR ELECTRICISTA DOMICILIARIO'
 'Diseño gráfico asistido por computadoras  i'
 'Administración de consorcios de propiedad horizontal'
 'OPERADOR INYECTOR' 'PROGRAMADOR INICIAL DE MÁQUINAS RECTILÍNEAS'
 'MECÁNICO DE BICICLETAS' 'OPERADOR DE HERRAMIENTAS DE MARKETING DIGITAL'
 'LEYES LABORALES' 'Depilación y manicuría' 'MODELADO 3D' 'PANADERO'
 'Programador' 'Asistente de producción de radio' 'Camarógrafo'
 'Depilación definitiva' 'Portugués con orientación técnico-comercial  I'
 'PELUQUERO/A' 'AUXILIAR CERAMISTA (MODULO I)'
 'Diseñador de páginas web  i'
 'INSTALADOR Y REPARADOR DE EQUIPOS DE CLIMATIZACIÓN'
 'Instalador y soporte de sistemas informáticos'
 'Instalador de sistemas de automatización' 'Liquidación de haberes'
 'Francés I' 'Asistente de producción de televisión' 'Mozo de salón'
 'Informática básica' 'DOCUMENTOS Y TRAMITES DEL AUTOMOTOR'
 'PRE-PRODUCCIÓN GRÁFICA' 'Soldador básico en eléctrica y autógena'
 'MECÁNICO DE TRANSMISIONES DEL AUTOMOTOR' 'Maquillador/a profesional'
 'Cerrajería'
 'Técnicas de oratoria (certifica como Auxiliar para la interpretación y lectura de textos para radio y televisión)'
 'Albañil' 'CARPINTERO DE BANCO'
 'Carpintero de hormigón armador cementista' 'Ayudante de contaduría'
 'Práctico en artesanías manuales' 'DISEÑO GRÁFICO Y EDITORIAL'
 'Inglés básico I' 'Diseño gráfico asistido por computadoras'
 'Coordinación de practicas corporales  i'
 'SEGURIDAD E HIGIENE EN EL TRABAJO'
 'Liquidación de sueldos de encargados de edificios de renta y horizontal'
 'Modelista - patronista' 'ELECTRICISTA DE AUTOMOTORES '
 'TALLER DE CRITICA DE CINE'
 'MONTADOR DE INSTALACIONES SANITARIAS DOMICILIARIAS' 'MECÁNICO DE MOTOS'
 'TRATAMIENTO Y RETOQUE DE IMÁGENES DIGITALES'
 'AUXILIAR DE PERIODISTA EN MEDIOS RADIALES'
 'Modelista interpretador. especialidad: lenceria, corseteria y mallas de damas     (1615)'
 'AUXILIAR DE CONTABILIDAD' 'Joyería' 'Serigrafía' 'Serigrafía básica'
 'Armador y montador de paneles y cielorrasos de placas de roca de yeso'
 'AUXILIAR EN INSTALACIONES SANITARIAS Y DE GAS DOMICILIARIAS'
 'Instructor de formación profesional'
 'COSTURA INDUSTRIAL EN MARROQUINERIA' 'EMPLEADO DE FARMACIA'
 'SECRETARIADO ADMINISTRATIVO' 'DISEÑO ASISTIDO POR COMPUTADORA'
 'Operador de sonido (certifica como Introducción al uso del ordenador en aplicaciones de sonido para radio y televisión)'
 'COMPUTACIÓN PARA SECRETARIAS Y OFICINISTAS I' 'FOTÓGRAFO/A'
 'Montador de instalaciones domiciliarias de gas'
 'Liquidación de sueldos y jornales' 'Confeccionista a medida. modista/o'
 'Editor audiovisual' 'Técnicas de ventas'
 'Especialista en tratamientos estético faciales'
 'TALLISTA EN YESO, MADERA Y PIEDRA I'
 'FORMACIÓN DEL SUPERVISOR EN GESTIÓN DE RECURSOS HUMANOS Y LIDERAZGO'
 'Portugués II' 'GOMERO BALANCEADOR' 'Inglés británico  I'
 'TALLER DE MOSAICO (MODULO I)'
 'Mecánico de  sistemas de encendido y alimentación'
 'AUXILIAR DE PERIODISTA EN MEDIOS TELEVISIVOS'
 'AUXILIAR MECANICO DE AUTOMOTORES' 'Empalmador en fibra óptica'
 'Ingles con orientación técnico-comercial  I'
 'COCINA DE PUEBLOS ORIGINARIOS I'
 'Diseño gráfico asistido por computadoras  ii'
 'Introducción a las tareas administrativas contables' 'AUXILIAR CONTABLE'
 'Retoque fotográfico por computadora' 'HERRERIA ARTISTICA Y DE OBRA'
 'MAQUINISTA IMPRESOR OFFSET'
 'Leyes laborales y aseguradoras de riesgo de trabajo (art)'
 'Estética corporal' 'Gestión total de calidad  i ( iso 9000 )'
 'OPERARIO  RECICLADOR' 'Auxiliar de gestión turística'
 'Instalador de sistemas eléctricos de energías renovables'
 'DISEÑO ASISTIDO POR COMPUTADORAS  I'
 'REALIZADOR DE VIDEOS DE EVENTOS SOCIALES' 'AUXILIAR DE CONSERJERIA'
 'Elaboración de productos multimediales  i' 'OPERADOR DE SONIDO I'
 'Seguridad informática i'
 'APRENDIZ ADMINISTRATIVO PARA LA INDUSTRIA PLASTICA'
 'Especialista en tratamientos estético corporales'
 'MONTAJE DE INSTALACIONES SANITARIAS' 'Cerrajería domiciliaria'
 'Gestión judicial' 'Carpintería en edificios'
 'Diseñador de páginas web  ii' 'TÉCNICAS DE DRENAJE LINFÁTICO MANUAL'
 'Estética facial' 'MARROQUINERIA' 'Diseño gráfico e ilustración digital'
 'AUXILIAR DE PERIODISTA EN MEDIOS GRÁFICOS' 'EXTRUSOR'
 'Instalador y reparador de redes  hfc' 'Comercialización'
 'Instalador y administrador de redes informáticas'
 'Ingles técnico superior' 'OPERADOR DE SOFTWARE ADMINISTRATIVO-CONTABLE'
 'INDUMENTARIA Y ELEMENTOS DE CRIANZA PARA EL BEBE'
 'OPERADOR DE IMÁGENES DIGITALES'
 'ACTUALIZACIÓN EN ADMINISTRACIÓN DE CONSORCIO'
 'INSTALACIONES TELEFONICAS DOMICILIARIAS'
 'TEJIDO SEMIINDUSTRIAL, INDUSTRIAL y MANUAL' 'ELECTRICISTA INDUSTRIAL'
 'SOLDADURA POR ARCO ELECTRICO' 'Reparación de electrodomésticos'
 'Taller de microemprendimientos' 'Asistente en gestión previsional'
 'SEGURIDAD E HIGIENE EN EL TRABAJO / EDIFICIOS'
 'OPERARIO DE MÁQUINA RECTILÍNEA'
 'Especialización Profesional en Programación WEB\t' 'Cadenas'
 'Técnicas artesanales (modulo: reciclado - vitofusión)'
 'Ingles: conversación i' 'Reparador básico de heladeras familiares'
 'Inglés básico III' 'Instalación  de ascensores' 'Portugués básico  i'
 'RELACIONES LABORALES Y ORIENTACIÓN PROFESIONAL (const)'
 'Experto en técnicas impositivas' 'EDICIÓN DE AUDIO DIGITAL I' 'Grabado'
 'AYUDANTE DE CONTADURIA' 'Coordinación de practicas corporales  ii'
 'AUXILIAR DE REGIDURIA DE PISOS' 'MONTADOR DE INSTALACIONES SANITARIAS'
 'INSTALADOR DE SISTEMAS SOLARES TÉRMICOS PARA AGUA CALIENTE SANITARIA'
 'HERRERO DE OBRA' 'INTRODUCCIÓN A LA ALFARERÍA EN TORNO'
 'TEJIDO SEMIINDUSTRIAL, INDUSTRIAL Y MANUAL NIVEL II'
 'Gasista Domiciliario' 'REALIZADOR DE GUIONES TELEVISIVOS'
 'Ingles para gestión pymes  i' 'Operario termoformador'
 'MAQUINISTA IMPRESOR OFFSET INICIAL'
 'Introducción al diseño aplicado a los talleres de oficios'
 'PINTURA DECORATIVA SOBRE MADERA O TELA'
 'FORMACIÓN DEL SUPERVISOR EN GESTIÓN DE LA PRODUCCIÓN'
 'MONTAJE DE INSTALACIONES DOMICILIARIAS DE GAS'
 'Ingles técnico intermedio'
 'DIBUJO DE PLANOS PARA INSTALACIONES DOMICILIARIAS'
 'LIDERAZGO Y GESTIÓN EN LA EMPRESA COOPERATIVA – GESTIÓN DE EQUIPOS'
 'AUXILIAR JURIDICO - CONTABLE' 'Ingles técnico básico'
 'TALLER DIBUJO/DISEÑO MANO ALZADA'
 'LAS HERRAMIENTAS INFORMATICAS PARA LA DIGITALIZACION DE IMAGENES'
 'OPERADOR DE MÁQUINA PARA LA CONFECCIÓN INDEMENTARIA'
 'PROGRAMACION INTERMEDIA DE SISTEMAS EMBEBIDOS'
 'COMUNICACIÓN ORGANIZACIONAL EN LA EMPRESA COOPERATIVA'
 'Electricista en inmuebles' 'PROGRAMADOR DE SISTEMAS EMBEBIDOS'
 'MEDICIONES EN CABLES TELEFONICOS DE PARES SIMETRICOS'
 'PINTURA SOBRE TELA' 'Terminación editorial'
 'MODELISTA INDUSTRIAL EN MARROQUINERIA'
 'Electricidad y electrónica básica en telecomunicaciones'
 'Portugués con orientación técnico-comercial  II'
 'Herramientas informáticas de gestión contable' 'ESTAMPADOR TEXTIL'
 'DECORADOR DE VIDRIERAS' 'Engarce'
 'Operador de torno especializado en arranque de viruta nivel basico'
 'ESPECIALIZACIÓN EN ADMINISTRACIÓN DE BASE DE DATOS (DBA)'
 'OPERADOR DE MAQUINA REMALLADORA' 'Inglés americano i' 'Cincelado'
 'Mecanico de sistemas de inyección diesel'
 'Mediciones y enlaces de fibra óptica'
 'MECÁNICO DE SISTEMAS DE FRENOS DEL AUTOMOTOR'
 'Dibujo técnico y documentación de obra' 'Francés iii'
 'Administrador de gestión pymes con orientación en comercialización'
 'TELEFONIA IP BAJO SISTEMAS DE CÓDIGO ABIERTO' 'Francés II' 'Telefonía'
 'Auxiliar topógrafo'
 'MARKETING DE SERVICIOS PROFESIONALES PARA EL ADMINISTRADOR DE CONSORCIOS'
 'MODELISTA SUPERIOR LINEA BEBE'
 'Mecánico de sistemas de suspensión y dirección del automotor'
 'Portugués III' 'Organización de empresas'
 'Modelista superior  linea bebe'
 'Ley de prenda con registro y credito prendario'
 'Reparación de artefactos a gas e instalación de sistemas de calefacción'
 'Cerrajería computarizada'
 'ESPECIALIZACIÓN PROFESIONAL EN PROGRAMACIÓN DE VIDEOJUEGOS'
 'INGLÉS BÁSICO  V' 'TEJIDO CON TELAR A MANO'
 'AUXILIAR EN CERAMICA ARTESANAL I'
 'Diseño gráfico asistido por computadoras  iv'
 'NEUMÁTICA E HIDRAULICA PARA LA INDUSTRIA PLÁSTICA'
 'OPERADOR DE TORNO NIVEL INCIAL' 'Pintor de obra y técnicas decorativas'
 'Auxiliar en herramientas informaticas juridico - contables'
 'ELABORACION DE PRODUCTOS MULTIMEDIALES  II']

Cantidad de filas por valor:
 curso
Pintor de obra y técnicas decorativas                                        1
ELABORACION DE PRODUCTOS MULTIMEDIALES  II                                   1
Auxiliar en herramientas informaticas juridico - contables                   1
DECORADOR DE VIDRIERAS                                                       3
PROGRAMADOR INICIAL DE MÁQUINAS RECTILÍNEAS                                  4
TALLISTA EN YESO, MADERA Y PIEDRA I                                          4
Mecánico de sistemas de suspensión y dirección del automotor                 4
ESPECIALIZACIÓN EN ADMINISTRACIÓN DE BASE DE DATOS (DBA)                     5
TEJIDO CON TELAR A MANO                                                      5
OPERADOR DE TORNO NIVEL INCIAL                                               7
Operador de torno especializado en arranque de viruta nivel basico           8
Portugués III                                                                8
Modelista superior  linea bebe                                               8
MARKETING DE SERVICIOS PROFESIONALES PARA EL ADMINISTRADOR DE CONSORCIOS     8
MAQUINISTA IMPRESOR OFFSET                                                   8
COMUNICACIÓN ORGANIZACIONAL EN LA EMPRESA COOPERATIVA                        9
Ley de prenda con registro y credito prendario                               9
INDUMENTARIA Y ELEMENTOS DE CRIANZA PARA EL BEBE                            10
MEDICIONES EN CABLES TELEFONICOS DE PARES SIMETRICOS                        10
Diseño gráfico asistido por computadoras  iv                                10
Name: curso, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 24245

Registros con variable "comision":
 24245

Cantidad de nulos:
 0

Valores distintos:
 ['Lu,Mi 20:40/23:00' 'Ma,Vi 15:30/18:00' 'Mi 14:10/17:00' ...
 'Ma,Ju 18:00/20:25' 'Ma,Ju 16:30/20:15' 'Lu,Mi,Vi 09:00/12:10']

Cantidad de filas por valor:
 comision
Ma,Ju 18:00/20:25       1
Ma 15:00/17:45          1
Ma,Ju 17:00/18:50       1
Ma,Ju 17:30/20:10       1
Mi,Vi 19:00/21:15       1
Lu,Ju,Vi 18:00/19:50    1
Mi,Vi 20:00/21:25       1
Lu,Mi 14:00/18:00       1
Vi 13:30/17:40          1
Ma 10:00/12:45          1
Lu,Ju 18:30/20:30       1
Sa 09:00/13:20          1
Lu,Vi 17:30/20:30       1
Lu,Vi 12:20/15:20       1
Lu,Vi 09:00/12:15       1
Lu,Mi,Vi 17:30/19:45    1
Lu,Mi,Vi 17:30/19:30    1
Ma,Ju 12:10/15:20       1
Lu,Ju 09:00/11:20       1
Lu 18:30/22:00          1
Name: comision, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 24245

Registros con variable "inscripcion":
 24245

Cantidad de nulos:
 0

Valores distintos:
 [34713409 34757962 35038204 ... 37964661 37130900 37434552]

Cantidad de filas por valor:
 inscripcion
34089852    1
37510363    1
37510310    1
37510078    1
37510072    1
37510008    1
37509981    1
37509965    1
37509949    1
37509832    1
37509781    1
37509735    1
37509688    1
37509430    1
37509319    1
37509238    1
37509172    1
37509117    1
37509052    1
37509040    1
Name: inscripcion, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 24245

Registros con variable "trabajo_relacionado":
 11271

Cantidad de nulos:
 12974

Valores distintos:
 ['NO' nan 'SI']

Cantidad de filas por valor:
 trabajo_relacionado
NO    4373
SI    6898
Name: trabajo_relacionado, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 24245

Registros con variable "motivo":
 11036

Cantidad de nulos:
 13209

Valores distintos:
 [nan 'Ampliar las posibilidades de conseguir trabajo' 'Recreación/Ocio']

Cantidad de filas por valor:
 motivo
Recreación/Ocio                                     255
Ampliar las posibilidades de conseguir trabajo    10781
Name: motivo, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 24245

Registros con variable "sorteo":
 0

Cantidad de nulos:
 24245

Valores distintos:
 [nan]

Cantidad de filas por valor:
 Series([], Name: sorteo, dtype: int64)
----------------------------------------------------------------------------------------------------
Filas totales:
 24245

Registros con variable "estado":
 24245

Cantidad de nulos:
 0

Valores distintos:
 ['VACANTE']

Cantidad de filas por valor:
 estado
VACANTE    24245
Name: estado, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 24245

Registros con variable "fechacreacion":
 24245

Cantidad de nulos:
 0

Valores distintos:
 ['2021-02-23 20:48:26.000' '2021-02-24 14:44:08.000'
 '2021-03-12 16:47:10.000' ... '2022-02-24 09:37:14.000'
 '2021-12-01 07:48:55.000' '2021-12-17 16:37:37.000']

Cantidad de filas por valor:
 fechacreacion
2020-12-01 00:37:40.000    1
2022-01-04 19:28:58.000    1
2022-01-04 19:20:56.000    1
2022-01-04 19:10:56.000    1
2022-01-04 19:05:00.000    1
2022-01-04 18:14:35.000    1
2022-01-04 18:00:14.000    1
2022-01-04 17:43:26.000    1
2022-01-04 17:31:49.000    1
2022-01-04 17:19:05.000    1
2022-01-04 17:02:10.000    1
2022-01-04 16:58:54.000    1
2022-01-04 16:56:55.000    1
2022-01-04 16:43:09.000    1

In [7]:
iel_cfp.get_resumen()

Analisis de completitud sin tener en cuenta ningún tipo de caracter especial, simplemente por valores nulos
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud

/home/anderson/Documents/analisis/monstry_goayvd/venv/lib/python3.10/site-packages/pandas/core/dtypes/astype.py:189: RuntimeWarning: invalid value encountered in cast
  return values.astype(dtype, copy=copy)

⚠️WARNING:
	LA COLUMNA "sorteo" ES COMPLETAMENTE NULA, POR LO TANTO VALOR DE EXACTITUD ES SETEADO A 0
Analisis de exactitud finalizado
* Para observar los resultados solo de "Exactitud" visualizar con .exactitud

,COLUMNA,NOMBRE TABLA,REGISTROS TOTALES,CANTIDAD DE INCOMPLETOS,CANTIDAD DE COMPLETOS,PORCENTAJE COMPLETITUD,EXACTO,INEXACTO,PORCENTAJE DE EXACTITUD
0,insert_into_dl_timestamp,iel_cfp,24245,0,24245,100.00,24245,0,100.00
1,nivel_estudios,iel_cfp,24245,0,24245,100.00,24245,0,100.00
2,profesion,iel_cfp,24245,0,24245,100.00,8787,15458,36.24
3,localidadprovincia,iel_cfp,24245,18330,5915,24.40,5859,56,99.05
4,provincia,iel_cfp,24245,0,24245,100.00,24245,0,100.00
5,direccion_estudiante,iel_cfp,24245,207,24038,99.15,24038,0,100.00
6,fecha_nacimiento,iel_cfp,24245,0,24245,100.00,24245,0,100.00
7,sexo,iel_cfp,24245,0,24245,100.00,24245,0,100.00
8,nacionalidad,iel_cfp,24245,0,24245,100.00,24244,1,100.00
9,telefono,iel_cfp,24245,3410,20835,85.94,20776,59,99.72
10,email,iel_cfp,24245,0,24245,100.00,24239,6,99.98
11,nrodocumento,iel_cfp,24245,5,24240,99.98,24134,106,99.56
12,tipo_documento,iel_cfp,24245,0,24245,100.00,24245,0,100.00
13,nombre,iel_cfp,24245,0,24245,100.00,24244,1,100.00
14,apellido,iel_cfp,24245,0,24245,100.00,24245,0,100.00
15,fechacreacion,iel_cfp,24245,0,24245,100.00,24245,0,100.00
16,estado,iel_cfp,24245,0,24245,100.00,24245,0,100.00
17,sorteo,iel_cfp,24245,24245,0,0.00,0,0,0.00
18,motivo,iel_cfp,24245,13209,11036,45.52,11036,0,100.00
19,trabajo_relacionado,iel_cfp,24245,12974,11271,46.49,11271,0,100.00
20,inscripcion,iel_cfp,24245,0,24245,100.00,24245,0,100.00
21,comision,iel_cfp,24245,0,24245,100.00,24245,0,100.00
22,curso,iel_cfp,24245,0,24245,100.00,23519,726,97.01
23,direccion_escuela,iel_cfp,24245,0,24245,100.00,24245,0,100.00
24,sede,iel_cfp,24245,0,24245,100.00,24245,0,100.00
25,nivel,iel_cfp,24245,0,24245,100.00,24245,0,100.00

In [8]:
iel_cfp.to_csv(file_name = "iel_cfp")

/home/anderson/Documents/analisis/monstry_goayvd/monstry

In [8]:
iel_cfp.__inexactos__()

--------------------------------------------nrodocumento--------------------------------------------
642      118152876
803     43769643-3
1350     361042020
1433     161667126
1867     PP5244108
Name: nrodocumento, dtype: object
----------------------------------------------telefono----------------------------------------------
1206          0
1394    4088942
4529          1
7465    1111111
8587    2330320
Name: telefono, dtype: object
-----------------------------------------------email------------------------------------------------
2806     GUILLERMO.SEMANIUK@CA1492.COM
20364          CHEGUILOPEZ@39GMAIL.COM
22839             susanasego32@yahoo.c
23086         DARIELGONZAAS@GMAILÑ.COM
23410         nahuel.reyna@3mar.com.ar
Name: email, dtype: object
-----------------------------------------------curso------------------------------------------------
15              DECORADOR ARTESANAL DE TORTAS (MODULO I)
38                         AUXILIAR CERAMISTA (MODULO I)
62     Técnicas de oratoria (certifica como Auxiliar ...
99     Modelista interpretador. especialidad: lenceri...
144    Operador de sonido (certifica como Introducció...
Name: curso, dtype: object
-----------------------------------------------nombre-----------------------------------------------
24117    J
Name: nombre, dtype: object
--------------------------------------------nacionalidad--------------------------------------------
14135    China (República Popular de)
Name: nacionalidad, dtype: object
-----------------------------------------localidadprovincia-----------------------------------------
516     Ciudad Autonoma de Bs. As.
702                            1714
1284                     9 de Julio
1349                     9 de abril
1769                     9 de julio
Name: localidadprovincia, dtype: object
---------------------------------------------profesion----------------------------------------------
2    (Otros...)
Name: profesion, dtype: object

In [9]:
iel_cfp.__exactos__()

--------------------------------------------nrodocumento--------------------------------------------
0    39426374
1    96091324
2    28815613
3    93966818
4    42624462
Name: nrodocumento, dtype: object
----------------------------------------------telefono----------------------------------------------
0    1130368383
1    1127287153
2    1134268251
3    1568863349
4    1165740810
Name: telefono, dtype: object
-----------------------------------------------email------------------------------------------------
0       m.angelicairibarren@gmail.com
1            giselaramirezu@gmail.com
2             ramirezmaia88@gmail.com
3                 ttechy258@gmail.com
4    arapacioli@entedelaciudad.gov.ar
Name: email, dtype: object
-----------------------------------------------curso------------------------------------------------
0                                         Portugués  I
1        Técnicas de liquidación de sueldos y jornales
2                                            PASTELERO
3    Operador de informática para administración y ...
4                               Auxiliar en cerámica i
Name: curso, dtype: object
-----------------------------------------------nombre-----------------------------------------------
0      Maria Angelica
1              Gisela
2               Carla
3             Esther
4    LAUTARO VALENTIN
Name: nombre, dtype: object
--------------------------------------------nacionalidad--------------------------------------------
0     Argentina
1     Venezuela
3          Perú
13       Brasil
17        Otros
Name: nacionalidad, dtype: object
-----------------------------------------localidadprovincia-----------------------------------------
9     Florida
14     beccar
19      MERLO
27      LANUS
31      Garin
Name: localidadprovincia, dtype: object
---------------------------------------------profesion----------------------------------------------
0                       Recepcionista
1                            Contable
3                 Cuidador/a de niños
5                             Docente
7    Profesor de enseñanza secundaria
Name: profesion, dtype: object