In [2]:
from monstry.Builder import Builder
from monstry.DataCleaner import DataCleaner

In [3]:
json_file = './analisis_calidad_iel_ifts/config/config.json'
builder = Builder( config_path = json_file)

Se ha creado usando un archivo de configuracion

In [4]:
iel_ifts = DataCleaner(builder, 'iel_ifts' )

Se ha cargado efectivamente el dataframe

        Informacion:
            _ get_completitud():
                Se obtienen la completutid de la tabla
            - get_exactitud():
                Se obtiene la exactitud de la tabla siempre y cuando los valores por default sean completados
                en el archivo de configuraciones o tengan un valor por defecto
            ----------------------------------------------------------------------------------------------------
            - get_resumen():
                Se obtiene un dataframe con el análisis de completitud y exactitud del dataset seleccionado

In [5]:
iel_ifts.get_completitud()
iel_ifts.completitud

Analisis de completitud sin tener en cuenta ningún tipo de caracter especial, simplemente por valores nulos
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud

,COLUMNA,NOMBRE TABLA,REGISTROS TOTALES,CANTIDAD DE INCOMPLETOS,CANTIDAD DE COMPLETOS,PORCENTAJE COMPLETITUD
0,insert_into_dl_timestamp,iel_ifts,6256,0,6256,100.00
1,turno,iel_ifts,6256,0,6256,100.00
2,supervisión,iel_ifts,6256,0,6256,100.00
3,establecimiento,iel_ifts,6256,0,6256,100.00
4,prov_alu,iel_ifts,6256,1,6255,99.98
5,barrio,iel_ifts,6256,4917,1339,21.40
6,partido,iel_ifts,6256,4174,2082,33.28
7,direccion,iel_ifts,6256,89,6167,98.58
8,certificadodiscapacidad,iel_ifts,6256,1,6255,99.98
9,disc_otros,iel_ifts,6256,6097,159,2.54
10,discmental,iel_ifts,6256,1,6255,99.98
11,epileptico,iel_ifts,6256,1,6255,99.98
12,discsensorial,iel_ifts,6256,1,6255,99.98
13,discmotora,iel_ifts,6256,1,6255,99.98
14,mail_creacion,iel_ifts,6256,0,6256,100.00
15,email,iel_ifts,6256,1396,4860,77.69
16,telefono,iel_ifts,6256,1395,4861,77.70
17,sistemasalud,iel_ifts,6256,1,6255,99.98
18,pais,iel_ifts,6256,1,6255,99.98
19,nrodocumento,iel_ifts,6256,4,6252,99.94
20,tipodocumento,iel_ifts,6256,1,6255,99.98
21,sexo,iel_ifts,6256,1,6255,99.98
22,apellido,iel_ifts,6256,1,6255,99.98
23,nombre,iel_ifts,6256,1,6255,99.98
24,fechanacimiento,iel_ifts,6256,1,6255,99.98
25,carrera,iel_ifts,6256,0,6256,100.00
26,disciplina,iel_ifts,6256,0,6256,100.00
27,fechacreacion,iel_ifts,6256,0,6256,100.00
28,nivel,iel_ifts,6256,0,6256,100.00
29,estado,iel_ifts,6256,0,6256,100.00
30,id,iel_ifts,6256,0,6256,100.00
31,año,iel_ifts,6256,0,6256,100.00

In [6]:
iel_ifts.get_exactitud()
iel_ifts.exactitud

Analisis de completitud sin tener en cuenta ningún tipo de caracter especial, simplemente por valores nulos
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud
Analisis de exactitud finalizado
* Para observar los resultados solo de "Exactitud" visualizar con .exactitud

                     COLUMNA  EXACTO  INEXACTO  PORCENTAJE DE EXACTITUD
0                      email    4858         2                    99.96
1              mail_creacion    6256         0                   100.00
2                        año    6256         0                   100.00
3                         id    6256         0                   100.00
4               nrodocumento    6244         8                    99.87
5                    carrera    6256         0                   100.00
6                     estado    6256         0                   100.00
7                      nivel    6256         0                   100.00
8                 disciplina    6256         0                   100.00
9                     nombre    6255         0                   100.00
10                  apellido    6255         0                   100.00
11                      pais    6255         0                   100.00
12              sistemasalud    6255         0                   100.00
13                disc_otros     149        10                    93.71
14                   partido    2082         0                   100.00
15                  prov_alu    6255         0                   100.00
16           establecimiento    4452      1804                    71.16
17               supervisión    6256         0                   100.00
18                     turno    5363       893                    85.73
19                      sexo    6255         0                   100.00
20             tipodocumento    6255         0                   100.00
21                  telefono    4859         2                    99.96
22             fechacreacion    6256         0                   100.00
23           fechanacimiento    6255         0                   100.00
24  insert_into_dl_timestamp    6256         0                   100.00
25                discmotora    6255         0                   100.00
26             discsensorial    6255         0                   100.00
27                epileptico    6255         0                   100.00
28                discmental    6255         0                   100.00
29   certificadodiscapacidad    6255         0                   100.00
30                 direccion    6049       118                    98.09
31                    barrio    1339         0                   100.00

In [7]:
iel_ifts.get_resumen()

Analisis de completitud sin tener en cuenta ningún tipo de caracter especial, simplemente por valores nulos
Analisis de completitud finalizado
 * Para observar los resultados solo de "Completitud" visualizar con .completitud
Analisis de exactitud finalizado
* Para observar los resultados solo de "Exactitud" visualizar con .exactitud

,COLUMNA,NOMBRE TABLA,REGISTROS TOTALES,CANTIDAD DE INCOMPLETOS,CANTIDAD DE COMPLETOS,PORCENTAJE COMPLETITUD,EXACTO,INEXACTO,PORCENTAJE DE EXACTITUD
0,insert_into_dl_timestamp,iel_ifts,6256,0,6256,100.00,6256,0,100.00
1,turno,iel_ifts,6256,0,6256,100.00,5363,893,85.73
2,supervisión,iel_ifts,6256,0,6256,100.00,6256,0,100.00
3,establecimiento,iel_ifts,6256,0,6256,100.00,4452,1804,71.16
4,prov_alu,iel_ifts,6256,1,6255,99.98,6255,0,100.00
5,barrio,iel_ifts,6256,4917,1339,21.40,1339,0,100.00
6,partido,iel_ifts,6256,4174,2082,33.28,2082,0,100.00
7,direccion,iel_ifts,6256,89,6167,98.58,6049,118,98.09
8,certificadodiscapacidad,iel_ifts,6256,1,6255,99.98,6255,0,100.00
9,disc_otros,iel_ifts,6256,6097,159,2.54,149,10,93.71
10,discmental,iel_ifts,6256,1,6255,99.98,6255,0,100.00
11,epileptico,iel_ifts,6256,1,6255,99.98,6255,0,100.00
12,discsensorial,iel_ifts,6256,1,6255,99.98,6255,0,100.00
13,discmotora,iel_ifts,6256,1,6255,99.98,6255,0,100.00
14,mail_creacion,iel_ifts,6256,0,6256,100.00,6256,0,100.00
15,email,iel_ifts,6256,1396,4860,77.69,4858,2,99.96
16,telefono,iel_ifts,6256,1395,4861,77.70,4859,2,99.96
17,sistemasalud,iel_ifts,6256,1,6255,99.98,6255,0,100.00
18,pais,iel_ifts,6256,1,6255,99.98,6255,0,100.00
19,nrodocumento,iel_ifts,6256,4,6252,99.94,6244,8,99.87
20,tipodocumento,iel_ifts,6256,1,6255,99.98,6255,0,100.00
21,sexo,iel_ifts,6256,1,6255,99.98,6255,0,100.00
22,apellido,iel_ifts,6256,1,6255,99.98,6255,0,100.00
23,nombre,iel_ifts,6256,1,6255,99.98,6255,0,100.00
24,fechanacimiento,iel_ifts,6256,1,6255,99.98,6255,0,100.00
25,carrera,iel_ifts,6256,0,6256,100.00,6256,0,100.00
26,disciplina,iel_ifts,6256,0,6256,100.00,6256,0,100.00
27,fechacreacion,iel_ifts,6256,0,6256,100.00,6256,0,100.00
28,nivel,iel_ifts,6256,0,6256,100.00,6256,0,100.00
29,estado,iel_ifts,6256,0,6256,100.00,6256,0,100.00
30,id,iel_ifts,6256,0,6256,100.00,6256,0,100.00
31,año,iel_ifts,6256,0,6256,100.00,6256,0,100.00

In [8]:
iel_ifts.analisis_por_categoria(*iel_ifts.columnas)

----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "año":
 6256

Cantidad de nulos:
 0

Valores distintos:
 [2021]

Cantidad de filas por valor:
 año
2021    6256
Name: año, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "id":
 6256

Cantidad de nulos:
 0

Valores distintos:
 [34471085 34385875 33468805 ... 35023094 34536668 35293209]

Cantidad de filas por valor:
 id
33330702    1
35012170    1
35011472    1
35010882    1
35010657    1
35010500    1
35010477    1
35009579    1
35009311    1
35009116    1
35012508    1
35009110    1
35008711    1
35006830    1
35006085    1
35005610    1
35005544    1
35005399    1
35005195    1
35000080    1
Name: id, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "estado":
 6256

Cantidad de nulos:
 0

Valores distintos:
 ['ESPERA' 'COMPLETA' 'VACANTE' 'ValidacionRechazada' 'Validada'
 'VALIDACIONPARCIAL' 'COMPLETATOTAL']

Cantidad de filas por valor:
 estado
COMPLETATOTAL             3
Validada                  3
VALIDACIONPARCIAL         7
ValidacionRechazada      77
VACANTE                 626
ESPERA                 2664
COMPLETA               2876
Name: estado, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "nivel":
 6256

Cantidad de nulos:
 0

Valores distintos:
 ['Terciario']

Cantidad de filas por valor:
 nivel
Terciario    6256
Name: nivel, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "fechacreacion":
 6256

Cantidad de nulos:
 0

Valores distintos:
 ['2021-02-02 12:55:46.563' '2020-12-31 18:43:36.996'
 '2020-10-13 14:29:25.458' ... '2021-03-11 17:41:59.661'
 '2021-02-12 14:33:51.349' '2021-07-05 12:25:44.432']

Cantidad de filas por valor:
 fechacreacion
2020-10-08 23:16:06.64     1
2021-03-10 22:44:01.899    1
2021-03-10 21:49:19.393    1
2021-03-10 21:06:32.5      1
2021-03-10 20:52:33.938    1
2021-03-10 20:42:22.782    1
2021-03-10 20:39:31.224    1
2021-03-10 19:28:08.532    1
2021-03-10 19:03:48.486    1
2021-03-10 18:53:44.108    1
2021-03-10 23:12:23.019    1
2021-03-10 18:53:15.023    1
2021-03-10 18:26:13.137    1
2021-03-10 16:39:12.638    1
2021-03-10 16:02:33.146    1
2021-03-10 15:42:29.455    1
2021-03-10 15:39:47.129    1
2021-03-10 15:33:32.561    1
2021-03-10 15:24:16.091    1
2021-03-10 15:05:35.503    1
Name: fechacreacion, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "disciplina":
 6256

Cantidad de nulos:
 0

Valores distintos:
 ['Salud y Seguridad Social' 'Tecnología' 'Energía' 'Automotriz']

Cantidad de filas por valor:
 disciplina
Automotriz                    58
Tecnología                   126
Energía                      160
Salud y Seguridad Social    5912
Name: disciplina, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "carrera":
 6256

Cantidad de nulos:
 0

Valores distintos:
 ['Enfermería profesional - (Res. 1436)'
 'Enfermería  profesional -  (Res. 1436) (Segundo Cuatrimestre)'
 'Facilitador Tecnológico Digital (Requisito: Título de Nivel Superior)'
 'Enfermería profesional - Plan para Auxiliares (Requisito: Titulo de Auxiliar en Enfermería) - Res. 1435'
 'Facilitador Tecnológico Digital (Requisito: Título de Nivel Superior) - (Segundo Cuatrimestre)'
 'Tecnicatura Superior en Gestión de Energías Renovables (Con Título de Media Técnica) - Segundo Cuatrimestre'
 'Tecnicatura Superior en Mantenimiento Industrial del Sector Automotriz (Requisito:  Título de Media Técnica)'
 'Enfermería profesional - Plan para Auxiliares (Requisito: Titulo de Auxiliar en Enfermería) - Res. 1435 (2do Cuatrimestre)'
 'Tecnicatura Superior en Distribución de la Energía Eléctrica (Requisito: Título de Media Técnica)'
 'Tecnicatura Superior en Gestión de Energías Renovables (Requisito: Título de Media Técnica)'
 'Tecnicatura Superior en Autotrónica (Requisito: Título de Media Técnica)'
 'Tecnicatura Superior en Distribución de la Energía Eléctrica (Con Título de Media Técnica) - Segundo Cuatrimestre']

Cantidad de filas por valor:
 carrera
Tecnicatura Superior en Autotrónica (Requisito: Título de Media Técnica)                                                        23
Tecnicatura Superior en Gestión de Energías Renovables (Con Título de Media Técnica) - Segundo Cuatrimestre                     26
Tecnicatura Superior en Distribución de la Energía Eléctrica (Con Título de Media Técnica) - Segundo Cuatrimestre               29
Tecnicatura Superior en Mantenimiento Industrial del Sector Automotriz (Requisito:  Título de Media Técnica)                    35
Facilitador Tecnológico Digital (Requisito: Título de Nivel Superior) - (Segundo Cuatrimestre)                                  48
Tecnicatura Superior en Distribución de la Energía Eléctrica (Requisito: Título de Media Técnica)                               50
Tecnicatura Superior en Gestión de Energías Renovables (Requisito: Título de Media Técnica)                                     55
Facilitador Tecnológico Digital (Requisito: Título de Nivel Superior)                                                           78
Enfermería profesional - Plan para Auxiliares (Requisito: Titulo de Auxiliar en Enfermería) - Res. 1435 (2do Cuatrimestre)     112
Enfermería profesional - Plan para Auxiliares (Requisito: Titulo de Auxiliar en Enfermería) - Res. 1435                        334
Enfermería  profesional -  (Res. 1436) (Segundo Cuatrimestre)                                                                 1799
Enfermería profesional - (Res. 1436)                                                                                          3667
Name: carrera, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "fechanacimiento":
 6255

Cantidad de nulos:
 1

Valores distintos:
 ['1994-05-20 00:00:00' '1981-05-20 00:00:00' '1994-11-18 00:00:00' ...
 '1992-01-17 00:00:00' '1967-08-03 00:00:00' '1989-12-30 00:00:00']

Cantidad de filas por valor:
 fechanacimiento
1954-10-24 00:00:00    1
1993-08-29 00:00:00    1
1993-09-02 00:00:00    1
1993-09-04 00:00:00    1
1993-09-05 00:00:00    1
1993-09-08 00:00:00    1
1993-09-13 00:00:00    1
1993-09-15 00:00:00    1
1993-09-17 00:00:00    1
1993-09-18 00:00:00    1
1993-09-20 00:00:00    1
1993-09-23 00:00:00    1
1993-09-28 00:00:00    1
1993-10-04 00:00:00    1
1993-10-07 00:00:00    1
1993-10-08 00:00:00    1
1993-10-09 00:00:00    1
1993-10-13 00:00:00    1
1993-10-15 00:00:00    1
1993-10-17 00:00:00    1
Name: fechanacimiento, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "nombre":
 6255

Cantidad de nulos:
 1

Valores distintos:
 ['Raquel Ayde' 'Shara Nathaly' 'leticia noemi' ... 'Antonela Ayelen'
 'Sofia Yanina ' 'nancy mabel']

Cantidad de filas por valor:
 nombre
 Ana Gabriela      1
Mirna              1
Mirta              1
Mirta Beatriz      1
Mirta Gisela       1
Mirta Graciela     1
Mirta Laura        1
Mirta antonella    1
Mirta azucena      1
Mirta ingrid       1
Mirtha             1
Mirtha Samanta     1
Misael             1
Moira              1
Mirian paola       1
Moises Enrique     1
Monica             1
Monica Adriana     1
Monica Griselda    1
Monica Viviana     1
Name: nombre, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "apellido":
 6255

Cantidad de nulos:
 1

Valores distintos:
 ['Mamani Choque' 'Ibañez Figueroa' 'fleitas alvarenga' ... 'Rocha Villa'
 'Lacamoida' 'gonzales rodriguez']

Cantidad de filas por valor:
 apellido
 Aviles Aranibar    1
Perrotta            1
Perruchino          1
Person              1
Pesqueira           1
Petrizzo            1
Petrone             1
Petzold Camacho     1
Peña Arambulo       1
Peña García         1
Peña caupy          1
Peñaloza            1
Perez Rodriguez     1
Peñaranda mamani    1
Pierola             1
Pierre              1
Pignanelli          1
Pilco Choque        1
Pinedo navarro      1
Pinedo sanchez      1
Name: apellido, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "sexo":
 6255

Cantidad de nulos:
 1

Valores distintos:
 ['Femenino' 'Masculino' nan]

Cantidad de filas por valor:
 sexo
Masculino    1392
Femenino     4863
Name: sexo, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "tipodocumento":
 6255

Cantidad de nulos:
 1

Valores distintos:
 ['DNI' nan 'CIE' 'CRE' 'DNX' 'PE' 'TRA' 'PN' 'SD']

Cantidad de filas por valor:
 tipodocumento
SD        1
PN        6
DNX      11
PE       11
TRA      13
CRE      14
CIE      22
DNI    6177
Name: tipodocumento, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "nrodocumento":
 6252

Cantidad de nulos:
 4

Valores distintos:
 ['95097706' '93603635' '38421995' ... '92718479' '41042497' '35031314']

Cantidad de filas por valor:
 nrodocumento
 43326930    1
42722292     1
42722260     1
42722194     1
42722170     1
42722057     1
42721856     1
42721472     1
42721413     1
42721309     1
42720818     1
42715025     1
42707917     1
42698784     1
42680851     1
42674489     1
42722293     1
42722323     1
42722684     1
42723090     1
Name: nrodocumento, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "pais":
 6255

Cantidad de nulos:
 1

Valores distintos:
 ['Bolivia' 'Perú' 'Argentina' 'Paraguay' 'Colombia' 'Venezuela' 'Brasil'
 'Uruguay' nan 'República Dominicana' 'Otros' 'Ecuador' 'Chile'
 'Estados Unidos' 'Italia' 'Rusia' 'España' 'Cuba' 'Afghanistán']

Cantidad de filas por valor:
 pais
Afghanistán                1
Italia                     1
Cuba                       1
España                     1
República Dominicana       2
Rusia                      2
Estados Unidos             3
Chile                      5
Ecuador                    6
Otros                      8
Brasil                     9
Uruguay                   10
Colombia                  32
Venezuela                 48
Paraguay                 146
Perú                     340
Bolivia                  948
Argentina               4692
Name: pais, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "sistemasalud":
 6255

Cantidad de nulos:
 1

Valores distintos:
 ['Hospital público' 'Obra social' 'Pre-paga' nan]

Cantidad de filas por valor:
 sistemasalud
Pre-paga             237
Obra social         1528
Hospital público    4490
Name: sistemasalud, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "telefono":
 4861

Cantidad de nulos:
 1395

Valores distintos:
 [1.13874734e+09 1.16621373e+09            nan ... 1.16562454e+09
 1.13421579e+09 1.13855351e+09]

Cantidad de filas por valor:
 telefono
4.302100e+05    1
1.160293e+09    1
1.160306e+09    1
1.160307e+09    1
1.160316e+09    1
1.160335e+09    1
1.160338e+09    1
1.160355e+09    1
1.160356e+09    1
1.160372e+09    1
1.160414e+09    1
1.160417e+09    1
1.160429e+09    1
1.160448e+09    1
1.160280e+09    1
1.160448e+09    1
1.160462e+09    1
1.160470e+09    1
1.160472e+09    1
1.160475e+09    1
Name: telefono, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "email":
 4860

Cantidad de nulos:
 1396

Valores distintos:
 ['raquel.e94m@gmail.com' 'shara_710@hotmail.com' nan ...
 'antonelachavez839@gmail.com' 'rigbys89@gmail.com'
 'mabelnancy982@gmail.com']

Cantidad de filas por valor:
 email
010272pietri@gmail.com            1
lucianasolis21@gmail.com          1
lucianayniguez@hotmail.com        1
luciaquintana198@gmail.com        1
luciasastre22@hotmail.com         1
luciazoeporcel@gmail.com          1
lucilamamani2021@gmail.com        1
lucilapinto20@gmail.com           1
lucilapm83@gmail.com              1
lucilarosad@gmail.com             1
lucilaswystun@gmail.com           1
lucio251877@gmail.com             1
lucizerp2001@gmail.com            1
ludfarias555@gmail.com            1
ludmila.braum@gmail.com           1
ludmila18073@gmail.com            1
ludmilabelenmilagros@gmail.com    1
ludmilacaasandra452@gmail.com     1
ludmilavera698@gmail.com          1
ludymanaos123@gmail.com           1
Name: email, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "mail_creacion":
 6256

Cantidad de nulos:
 0

Valores distintos:
 ['raquel.e94m@gmail.com' 'shara_710@hotmail.com'
 'noemifleitas10@gmail.com' ... 'celeste.copa1@gmail.com'
 'antonelachavez839@gmail.com' 'Rigbys89@gmail.com']

Cantidad de filas por valor:
 mail_creacion
010272pietri@gmail.com               1
luliixavier58@gmail.com              1
luks_90_81@hotmail.com               1
lujandelgadocrisanabel@gmail.com     1
lujan.pablo@gmail.com                1
luisnsalinas@hotmail.com.ar          1
luisivan8815@hotmail.com             1
luisitoshop@gmail.com                1
luisarmandocruzperez701@gmail.com    1
luisangelgabriel2@gmail.com          1
luisanaalfaro23@gmail.com            1
luisana160212@gmail.com              1
luisacalderon1405@gmail.com          1
luisaalmaraz8@gmail.com              1
luisa.revol@bue.edu.ar               1
luhanacastillo0@gmail.com            1
lulijaimee@gmail.com                 1
lulutori91@gmail.com                 1
lulydbf@gmail.com                    1
lumuwenz1995@gmail.com               1
Name: mail_creacion, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "discmotora":
 6255

Cantidad de nulos:
 1

Valores distintos:
 [ 0.  1. nan]

Cantidad de filas por valor:
 discmotora
1.0      33
0.0    6222
Name: discmotora, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "discsensorial":
 6255

Cantidad de nulos:
 1

Valores distintos:
 [ 0. nan  1.]

Cantidad de filas por valor:
 discsensorial
1.0       3
0.0    6252
Name: discsensorial, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "epileptico":
 6255

Cantidad de nulos:
 1

Valores distintos:
 [ 0. nan  1.]

Cantidad de filas por valor:
 epileptico
1.0      10
0.0    6245
Name: epileptico, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "discmental":
 6255

Cantidad de nulos:
 1

Valores distintos:
 [ 0.  1. nan]

Cantidad de filas por valor:
 discmental
1.0     247
0.0    6008
Name: discmental, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "disc_otros":
 159

Cantidad de nulos:
 6097

Valores distintos:
 [nan 'Asma e hipotiroidismo' 'C.A de Cervix en tratamiento.' 'Diabetes'
 'Asma' 'Migraña' 'Tiroides' 'Miopia' 'Hipertensa e hipotiroidea'
 'asmatica ' 'Obesidad ' 'Diabetes Mellitus tipo I' 'Linfoma en remisión'
 'diabetes' 'lupus eritematoso sistemico ' 'ASMA- TIROIDE'
 'Problemas cardiacos ' 'Hipertenso ' 'Cáncer de mama' 'Anemia cronica'
 'Hipotiroidismo' 'cardiacos, presion, respiratorios'
 'Colesterol  y triglicéridos altos ' 'Hemofilia ' 'Asma ' 'Deabetis'
 'SOY ASMATICA CRONICO' 'Diabetes tipo 1'
 'Tengo Gastritis Crónica y Colon Irritable.' 'Dbt 2'
 'Tomo medicación para la tiroides'
 'Asma leve, en tratamiento y controlado.' 'angina vaso espástica' 'Lupus'
 'Protesis ortopédica pie derecho' 'En tratamiento leucemia'
 'Tengo asma bronquial crónico, uso el pasf.' 'Artritis' 'Inmunodepresivo'
 'Asma intermitente aguda severa ' 'hipotiroidismo'
 'ENFERMEDAD RESPIRATORIA' 'Broncoespasmo' 'Dbt tipo2'
 'Hipertensión,disminución visual' 'HIV (indetectable' 'Dislexia severa'
 'Diabetes ' 'Miopia maculopatia' 'operada de tiroides'
 'Transtorno de ansiedad ' 'Rosácea' 'celiaquía '
 'chagas de nacimiento y fui operada por una hernia umbilical recientemente'
 'Bronquiectaseas' 'Diabetes 2' 'Miopia y aftimatismo' 'Un solo riñón '
 'Hipotiroidismo ' 'Psoriasis' 'psicologica' 'Cardiacos'
 'Inmunodeficiencia' 'tengo hipotiroidismo'
 'operacion reciente por apendicitis' 'Chagas' 'Esclerodermia '
 'Arritmia medicada' 'artritis reumatoidea' 'esquizofrenia' 'Hipertenso'
 'Asma, hipotiroidismo.' 'fibromialgia - miomas uterinos ' 'Rosasea'
 'Hipertensa. migraña' 'CARDIOPATIA CONGENITA' 'Hipertension Arterial'
 'Trastorno esquizo afectivo tipo depresivo' 'Esquizofrenia' 'Prediabetes'
 'Arritmia' 'Paciente oncologico' 'motora'
 'Operado de cataratas en ambos ojos ' 'asma' 'Asma crónica ' 'Dibetica'
 'soplo leve' 'hipertensa' 'Astigmatismo' 'Viceral' 'Asma crónico'
 'Alergica al limon en embase' 'hipotiroidismo, diabetes'
 'Operada del corazón a los siete meses de vida'
 'Enfermedad respiratoria ' 'diabetico y celiaco' 'ASMA CRONICA'
 'Hipertensión' 'Osugra' 'Hipotiroides' 'DIABETES-HIPERTENSION'
 'Tuberculosis pulmonar' 'Trastorno límite de la personalidad'
 'Tengo Hipertiroidismo' 'Artrosis, dolores lumbares' 'Psicólogica/mental']

Cantidad de filas por valor:
 disc_otros
ASMA CRONICA                                     1
SOY ASMATICA CRONICO                             1
Rosácea                                          1
Rosasea                                          1
Psoriasis                                        1
Psicólogica/mental                               1
Protesis ortopédica pie derecho                  1
Problemas cardiacos                              1
Prediabetes                                      1
Paciente oncologico                              1
Tengo Hipertiroidismo                            1
Osugra                                           1
Operada del corazón a los siete meses de vida    1
Obesidad                                         1
Miopia y aftimatismo                             1
Miopia maculopatia                               1
Migraña                                          1
Linfoma en remisión                              1
Inmunodepresivo                                  1
Inmunodeficiencia                                1
Name: disc_otros, dtype: int64
----------------------------------------------------------------------------------------------------
Filas totales:
 6256

Registros con variable "certificadodiscapacidad":
 6255

Cantidad de nulos:
 1

Valores distintos:
 [ 0.  1. nan]

Cantidad de filas por valor:
 certificadodiscapacidad
1.0      58
0.0    6197
Name: certificadodiscapacidad, dtype: int64

In [7]:
iel_ifts.to_csv(file_name = "iel_ifts")

/home/anderson/Documents/analisis/monstry_goayvd/monstry

In [8]:
iel_ifts.__inexactos__()
iel_ifts.__exactos__()

-----------------------------------------------email------------------------------------------------
959     nilagonsalez@21gmail.com
2873    vargasalbert@29gmail.com
Name: email, dtype: object
---------------------------------------------direccion----------------------------------------------
73                                              9
117    BONORINO, ESTEBAN, CNEL. AV. y RIESTRA AV.
251                                             4
270                  DIAZ, AVELINO y CARABOBO AV.
317          Boulogne sur mer y antofagasta s/n.
Name: direccion, dtype: object
--------------------------------------------nrodocumento--------------------------------------------
453      N07937413
465      Pp4091981
2881     PP5244108
3357    39.230.912
4143      AT114010
Name: nrodocumento, dtype: object
---------------------------------------------disc_otros---------------------------------------------
103                  C.A de Cervix en tratamiento.
1107                               Diabetes tipo 1
1174    Tengo Gastritis Crónica y Colon Irritable.
1201                                         Dbt 2
1360       Asma leve, en tratamiento y controlado.
Name: disc_otros, dtype: object
------------------------------------------establecimiento-------------------------------------------
2     Esc. Superior de Enfermería Dra. Cecilia Grier...
25    Instituto de Formación Técnica Superior Nº 30 ...
55    Instituto de Formación Técnica Superior Nº 32 ...
82    Instituto de Formación Técnica Superior Nº 31 ...
Name: establecimiento, dtype: object
-----------------------------------------------turno------------------------------------------------
7     13:00 a 18:00
65    13:30 a 18:30
Name: turno, dtype: object
----------------------------------------------telefono----------------------------------------------
5742     430210
6165    4466737
Name: telefono, dtype: object
-----------------------------------------------email------------------------------------------------
0          raquel.e94m@gmail.com
1          shara_710@hotmail.com
6         alarconirasi@gmail.com
7    aracelimallea22@hotmail.com
8       andreacocarico@gmail.com
Name: email, dtype: object
---------------------------------------------direccion----------------------------------------------
0                        Sayos 5321
1                     Jose Pico 345
2                   plumerillo 3924
4    CHUTRO, PEDRO, PROF., DR. 2495
5                Primera Junta 1145
Name: direccion, dtype: object
--------------------------------------------nrodocumento--------------------------------------------
0    95097706
1    93603635
2    38421995
3    94304471
4    40918850
Name: nrodocumento, dtype: object
---------------------------------------------disc_otros---------------------------------------------
4      Asma e hipotiroidismo
125                 Diabetes
142                     Asma
166                  Migraña
254                 Tiroides
Name: disc_otros, dtype: object
------------------------------------------establecimiento-------------------------------------------
0    Esc. Superior de Enfermería Dra. Cecilia Grierson
Name: establecimiento, dtype: object
-----------------------------------------------turno------------------------------------------------
0          Tarde
1          Noche
2         Mañana
25    Vespertino
Name: turno, dtype: object
----------------------------------------------telefono----------------------------------------------
0    1138747335
1    1166213729
6    1527857485
7    1138466311
8    1159292828
Name: telefono, dtype: object